/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sergio;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;


/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 * To build:
 * ./gradlew build
 */
public class App {
    public static void main(String... args) {
        List<Integer> example = new ArrayList<>();
        int min = 0;
        int max = 100;
        IntStream.range(min,max).forEach(example::add);
        System.out.println(Lists.reverse(example));
    }
}
